### ISSUE TITLE
Arduino serial messages and keyboard don't work with wsadqe

### ISSUE THREAD

**Issue by Slattsveen** [trolllabs/eduROV#6]
There is no response from the Arduino with the current html-setup when I press the wsadqe buttons. The arduino does respond to Serial message on the format 0000 when sent directly over the Serial monitor :)

Also, sensor data is now sent over serial every 100milliseconds. Format: 18:24.41:104.09:9.05, message details: "length:temperature:pressure:battery voltage"

**Comment by martinloland** [comment]
are you using the send and receive functions as in arduino_code/communication.ino? Serial communication from python will start with a 6-byte hex describing the length of the preceeding message, the receive_signal() function will then remove these bytes before it returns the string. The same for sending messages from arduino to python. Python expects that messages sent to it over serial will start with a 6-byte  hex number describing the length of the message. The send_signal(String msg) function is used for this.

**Example:**
_Python:_
send_arduino('hello there', serial_connection) will send: "0x000bhello there" over serial.
_Arduino:_
receive_signal() will then return: "hello there" as a String

_Arduino:_
String msg = "i am arduino";
send_signal(msg) will send "0x000ci am arduino" over serial to python:
_Python:_
receive_arduino(serial_connection) will return "i am arduino"

**Comment by Slattsveen** [comment]
Updated message formatting on the Arduino, works fine now! 👍
