### ISSUE TITLE
Video feed drops out

### ISSUE THREAD

**Issue by Slattsveen** [trolllabs/eduROV#9]
Might be a local problem.. But my video feed drops out after a few seconds. :(

![edurov_novideo](https://user-images.githubusercontent.com/22937548/37585149-634dc8b4-2b58-11e8-98ea-335f27e98fa0.PNG)

**Comment by Slattsveen** [comment]
![video_feed_drop_out_error](https://user-images.githubusercontent.com/22937548/37587099-937e7924-2b5e-11e8-97e0-99c8eb6565a5.PNG)

**Comment by martinloland** [comment]
belongs to an old version, marked as closed for now. can be reopened if the problem persists.
